version: '3'
services:
  web:
    build: .
    tty: True
    command: bash
    volumes:
      - .:/app
      - ./docker.env:/app/dostuff/.env
    ports:
      - "5000:5000"
  redis:
    image: redis:5.0.7
