version: '3'
services:
  web:
    build: .
    tty: True
    command: bash
    volumes:
      - .:/app
      - ./docker.env:/app/dostuff/.env
    ports:
      - 127.0.0.1:5000:5000
  redis:
    image: redis:5.0.7
